### ISSUE TITLE
Activity

### ISSUE THREAD

**Issue by NileFrater** [particlebanana/machinepack-stripe#3]
Is this repo active? I feel like I'm clogging up node-machine.org having a separate NPM but the pull request has been open for a while and I'm reluctant to add the other machines I've created for now.  Is someone actively maintaining this or would I be best running an alternative?

**Comment by particlebanana** [comment]
Sorry @NileFrater I can make you a collaborator on this if you want.

**Comment by NileFrater** [comment]
That would be great, Cody

Cheers!

—
