### ISSUE TITLE
deleteCard customerId error

### ISSUE THREAD

**Issue by galcivar** [particlebanana/machinepack-stripe#4]
Hi!
When I call Stripe.deleteCard({api,card_id}).

I get the following error:
[Error: Stripe: I require argument "customerId", but I got: undefined]

If i try to pass customerId directly it does not work.

The reference of the machine-pack in (http://node-machine.org/machinepack-stripe/delete-card) says that no customerId is required.

Is it a bug or am I doing something wrong?
Best

**Comment by galcivar** [comment]
I just tried using customer (instead of customerId) and it worked, I guess its the documentation that needs a tiny update! Anyhow, thanks for the good work!

**Comment by NileFrater** [comment]
I was just about to get back to you on this. The argument is customer as you said, I'll update the inputs to reflect this error message across the board.

**Comment by rachaelshaw** [comment]
@NileFrater @galcivar I had some trouble with this machine too, fixed in 3.0
